# Generated by Django 6.0.2 on 2026-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('openness_score', models.FloatField()),
                ('conscientiousness_score', models.FloatField()),
                ('extraversion_score', models.FloatField()),
                ('agreeableness_score', models.FloatField()),
                ('neuroticism_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
